### PR TITLE
Bug 1139508: Update media paths

### PR DESCRIPTION
**Pull request by openjck**
MDN assets are moving with pull request 3099 [1]. This change updates
the paths accordingly.

[1] https://github.com/mozilla/kuma/pull/3099

### CODE REVIEW

**Comment by stephaniehobson** [comment]
Looks good to me! R+

Not sure what the process is for pushing this. It needs to go in conjunction with the PR cited above.

**Comment by openjck** [comment]
I think it takes effect immediately when merged. Is that right @groovecoder?

**Comment by groovecoder** [comment]
Sadly, no. We have to make a new release to PyPI:

https://pypi.python.org/pypi/mdn-sphinx-theme/

**Comment by openjck** [comment]
Anything I can do to help push this forward?

**Comment by groovecoder** [comment]
Sorry I dropped this. I just added [a card to our TO DO column](https://trello.com/c/J1uElLm1/485-make-mdn-sphinx-theme-release-on-pypi) so it doesn't disappear completely.

**Pull request merged**
