### PR TITLE
bug 1133585 - update theme; and proper favicon

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by groovecoder** [comment]
After this is merged, I'll upload the new package to PyPI.

**Comment by groovecoder** [comment]
https://github.com/mozilla/kuma/pull/3088 is merged. Just need this to merge too then I can make the PyPI release.

**Comment by jezdez** [comment]
Seems like this needs to be rebased now that #4 got merged

**Comment by jwhitlock** [comment]
Closing in favor of #10

**Pull request closed without merging**
